# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamjub', '0002_auto_20161113_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cid', models.CharField(max_length=32, unique=True)),
                ('name', models.TextField()),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='picture',
            field=models.ImageField(null=True, upload_to='faces/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('foundation-year', 'Foundation Year'), ('medprep', 'Medprep'), ('undergrad', 'Undergraduate'), ('master', 'Master'), ('phd-integrated', 'integrated PhD'), ('phd', 'PhD'), ('winter', 'Winter School Student'), ('guest', 'Guest Student')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(to='dreamjub.Student'),
        ),
    ]
