# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-04 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamjub', '0003_auto_20161203_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cid',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
