# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dreamjub', '0003_auto_20161204_2258'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LocalStudent',
        ),
    ]
