# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dreamjub', '0003_auto_20161201_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(to='dreamjub.Student'),
        ),
    ]
